version: '3'

######### Services ###################################

services:
  # Server container
  nginx:
    build:
      context: docker/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www
    ports:
      # Client port
      - 80:80
      - 1337:1337
    links:
      - client
      - api
  # Strapi
  api:
    build:
      context: docker/api
      dockerfile: Dockerfile
    environment:
      DATABASE_CLIENT: mysql
      DATABASE_HOST: mariadb
      DATABASE_PORT: 3306
      DATABASE_NAME: strapi
      DATABASE_USERNAME: strapi
      DATABASE_PASSWORD: strapi
      DATABASE_SSL: 'false'
    volumes:
      - ./api:/var/www/api
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:latest
    volumes:
      - database:/var/lib/mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: strapi
      MYSQL_DATABASE: strapi
      MYSQL_USER: strapi
      MYSQL_PASSWORD: strapi
  # Nuxt
  client:
    build:
      context: docker/client
      dockerfile: Dockerfile
    volumes:
      - ./client:/var/www/client

volumes:
  database:
    driver: local